version: '2'
services:
  proxy-docker:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /home/rmadmin/log/nginx:/var/log/nginx/
      - /home/rmadmin/ssl:/ssl/
networks:
    default:
      external:
        name: project-net
# Edit by ArtidSun