version: '2'
services:
  proxy-docker:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /home/dev371/dohttps/data/.well-known/pki-validation:/usr/share/nginx/html/.well-known/pki-validation/
      - /home/dev371/dohttps/nginx:/var/log/nginx/
      - /home/dev371/dohttps/ssl:/ssl/
networks:
    default:
      external:
        name: project-net